//action types for pages
export const INIT_MAINPAGE_TRIGGERED = "INIT_MAINPAGE_TRIGGERED";
export const INIT_MAINPAGE_REQUEST = "INIT_MAINPAGE_REQUEST";
export const INIT_MAINPAGE_SUCCESS = "INIT_MAINPAGE_SUCCESS";
export const INIT_MAINPAGE_FAILURE = "INIT_MAINPAGE_FAILURE";

export const INIT_CONFIRMPAGE_TRIGGERED = "INIT_CONFIRMPAGE_TRIGGERED";
export const INIT_CONFIRMPAGE_REQUEST = "INIT_CONFIRMPAGE_REQUEST";
export const INIT_CONFIRMPAGE_SUCCESS = "INIT_CONFIRMPAGE_SUCCESS";
export const INIT_CONFIRMPAGE_FAILURE = "INIT_CONFIRMPAGE_FAILURE";

export const INIT_DESIGNERPORTFOLIOPAGE_TRIGGERED =
  "INIT_DESIGNERPORTFOLIOPAGE_TRIGGERED";
export const INIT_DESIGNERPORTFOLIOPAGE_REQUEST =
  "INIT_DESIGNERPORTFOLIOPAGE_REQUEST";
export const INIT_DESIGNERPORTFOLIOPAGE_SUCCESS =
  "INIT_DESIGNERPORTFOLIOPAGE_SUCCESS";
export const INIT_DESIGNERPORTFOLIOPAGE_FAILURE =
  "INIT_DESIGNERPORTFOLIOPAGE_FAILURE";

export const INIT_FAQPAGE_TRIGGERED = "INIT_FAQPAGE_TRIGGERED";
export const INIT_FAQPAGE_REQUEST = "INIT_FAQPAGE_REQUEST";
export const INIT_FAQPAGE_SUCCESS = "INIT_FAQPAGE_SUCCESS";
export const INIT_FAQPAGE_FAILURE = "INIT_FAQPAGE_FAILURE";

export const INIT_ALBUMEXAMPLESPAGE_TRIGGERED =
  "INIT_ALBUMEXAMPLESPAGE_TRIGGERED";
export const INIT_ALBUMEXAMPLESPAGE_REQUEST = "INIT_ALBUMEXAMPLESPAGE_REQUEST";
export const INIT_ALBUMEXAMPLESPAGE_SUCCESS = "INIT_ALBUMEXAMPLESPAGE_SUCCESS";
export const INIT_ALBUMEXAMPLESPAGE_FAILURE = "INIT_ALBUMEXAMPLESPAGE_FAILURE";

export const SEND_CONTACT_INFO_TRIGGERED = "SEND_CONTACT_INFO_TRIGGERED";
export const SEND_CONTACT_INFO_REQUEST = "SEND_CONTACT_INFO_REQUEST";
export const SEND_CONTACT_INFO_SUCCESS = "SEND_CONTACT_INFO_SUCCESS";
export const SEND_CONTACT_INFO_FAILURE = "SEND_CONTACT_INFO_FAILURE";

export const SEND_GIFT_CARD_TRIGGERED = "SEND_GIFT_CARD_TRIGGERED";
export const SEND_GIFT_CARD_REQUEST = "SEND_GIFT_CARD_REQUEST";
export const SEND_GIFT_CARD_SUCCESS = "SEND_GIFT_CARD_SUCCESS";
export const SEND_GIFT_CARD_FAILURE = "SEND_GIFT_CARD_FAILURE";
// ---------------------------------------------------------------------------
//(contact us)
export const CONTACT_US_TRIGGERED = "CONTACT_US_TRIGGERED";
export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";

export const GIFT_CARD_TRIGGERED = "GIFT_CARD_TRIGGERED";
export const GIFT_CARD_REQUEST = "GIFT_CARD_REQUEST";
export const GIFT_CARD_SUCCESS = "GIFT_CARD_SUCCESS";
export const GIFT_CARD_FAILURE = "GIFT_CARD_FAILURE";

//albums
export const INIT_ALBUMS_TRIGGERED = "INIT_ALBUMS_TRIGGERED";
export const INIT_ALBUMS_REQUEST = "INIT_ALBUMS_REQUEST";
export const INIT_ALBUMS_SUCCESS = "INIT_ALBUMS_SUCCESS";
export const INIT_ALBUMS_FAILURE = "INIT_ALBUMS_FAILURE";
//images
export const INIT_IMAGES_TRIGGERED = "INIT_IMAGES_TRIGGERED";
export const INIT_IMAGES_REQUEST = "INIT_IMAGES_REQUEST";
export const INIT_IMAGES_SUCCESS = "INIT_IMAGES_SUCCESS";
export const INIT_IMAGES_FAILURE = "INIT_IMAGES_FAILURE";
//marks
export const MARK_PLACED = "MARK_PLACED";

export const INIT_ORDERPAGE_TRIGGERED = "INIT_ORDERPAGE_TRIGGERED";
export const INIT_ORDERPAGE_REQUEST = "INIT_ORDERPAGE_REQUEST";
export const INIT_ORDERPAGE_SUCCESS = "INIT_ORDERPAGE_SUCCESS";
export const INIT_ORDERPAGE_FAILURE = "INIT_ORDERPAGE_FAILURE";
export const SEND_COMMENTS_SUMBITTED = "SEND_COMMENTS_SUMBITTED";
export const SEND_COMMENTS_REQUEST = "SEND_COMMENTS_REQUEST";
export const SEND_COMMENTS_SUCCESS = "SEND_COMMENTS_SUCCESS";
export const SEND_COMMENTS_FAILURE = "SEND_COMMENTS_FAILURE";

export const INIT_LOGINPAGE_TRIGGERED = "INIT_LOGINPAGE_TRIGGERED";
export const INIT_LOGINPAGE_REQUEST = "INIT_LOGINPAGE_REQUEST";
export const INIT_LOGINPAGE_SUCCESS = "INIT_LOGINPAGE_SUCCESS";
export const INIT_LOGINPAGE_FAILURE = "INIT_LOGINPAGE_FAILURE";
export const CHECK_PROMOCODE_SUMBITTED = "CHECK_PROMOCODE_SUMBITTED";
export const CHECK_PROMOCODE_REQUEST = "CHECK_PROMOCODE_REQUEST";
export const CHECK_PROMOCODE_SUCCESS = "CHECK_PROMOCODE_SUCCESS";
export const CHECK_PROMOCODE_FAILURE = "CHECK_PROMOCODE_FAILURE";

export const INIT_THANKYOUPAGE_TRIGGERED = "INIT_THANKYOUPAGE_TRIGGERED";
export const INIT_THANKYOUPAGE_REQUEST = "INIT_THANKYOUPAGE_REQUEST";
export const INIT_THANKYOUPAGE_SUCCESS = "INIT_THANKYOUPAGE_SUCCESS";
export const INIT_THANKYOUPAGE_FAILURE = "INIT_THANKYOUPAGE_FAILURE";

export const INIT_REQUESTPAGE_TRIGGERED = "INIT_REQUESTPAGE_TRIGGERED";
export const INIT_REQUESTPAGE_REQUEST = "INIT_REQUESTPAGE_REQUEST";
export const INIT_REQUESTPAGE_SUCCESS = "INIT_REQUESTPAGE_SUCCESS";
export const INIT_REQUESTPAGE_FAILURE = "INIT_REQUESTPAGE_FAILURE";

//action types for components
export const INIT_FLIPPER_TRIGGERED = "INIT_FLIPPER_TRIGGERED";
export const INIT_FLIPPER_REQUEST = "INIT_FLIPPER_REQUEST";
export const INIT_FLIPPER_SUCCESS = "INIT_FLIPPER_SUCCESS";
export const INIT_FLIPPER_FAILURE = "INIT_FLIPPER_FAILURE";

export const INIT_SIDEBAR_TRIGGERED = "INIT_SIDEBAR_TRIGGERED";
export const INIT_SIDEBAR_REQUEST = "INIT_SIDEBAR_REQUEST";
export const INIT_SIDEBAR_SUCCESS = "INIT_SIDEBAR_SUCCESS";
export const INIT_SIDEBAR_FAILURE = "INIT_SIDEBAR_FAILURE";

export const INIT_HEADERFOOTER_TRIGGERED = "INIT_HEADERFOOTER_TRIGGERED";
export const INIT_HEADERFOOTER_REQUEST = "INIT_HEADERFOOTER_REQUEST";
export const INIT_HEADERFOOTER_SUCCESS = "INIT_HEADERFOOTER_SUCCESS";
export const INIT_HEADERFOOTER_FAILURE = "INIT_HEADERFOOTER_FAILURE";

export const INIT_ORDER_IMAGES_TRIGGERED = "INIT_ORDER_IMAGES_TRIGGERED";
export const INIT_ORDER_IMAGES_REQUEST = "INIT_ORDER_IMAGES_REQUEST";
export const INIT_ORDER_IMAGES_SUCCESS = "INIT_ORDER_IMAGES_SUCCESS";
export const INIT_ORDER_IMAGES_FAILURE = "INIT_ORDER_IMAGES_FAILURE";
export const CLEAR_IMAGES = "CLEAR_IMAGES";

//action types for internazional
export const SWITCH_LOCALE = "SWITCH_LOCALE";

//send session data
export const SEND_SESSION_SUMBITTED = "SEND_SESSION_SUMBITTED";
export const SEND_SESSION_REQUEST = "SEND_SESSION_REQUEST";
export const SEND_SESSION_SUCCESS = "SEND_SESSION_SUCCESS";
export const SEND_SESSION_FAILURE = "SEND_SESSION_FAILURE";
//send marks
export const REDUX_FORM_BLUR = "REDUX_FORM_BLUR";
//send location
export const SEND_LOCATION_DATA_TRIGGERED = "SEND_LOCATION_DATA_TRIGGERED";
export const SEND_LOCATION_DATA_REQUEST = "SEND_LOCATION_DATA_REQUEST";
export const SEND_LOCATION_DATA_SUCCESS = "SEND_LOCATION_DATA_SUCCESS";
export const SEND_LOCATION_DATA_FAILURE = "SEND_LOCATION_DATA_FAILURE";

export const SEND_READY_ORDER_TRIGGERED = "SEND_READY_ORDER_TRIGGERED";
export const SEND_READY_ORDER_REQUEST = "SEND_READY_ORDER_REQUEST";
export const SEND_READY_ORDER_SUCCESS = "SEND_READY_ORDER_SUCCESS";
export const SEND_READY_ORDER_FAILURE = "SEND_READY_ORDER_FAILURE";
